[env:esp32-s3]
platform = espressif32@6.10.0
board = esp32-s3-n16r8
framework = arduino

board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.filesystem = littlefs

build_flags =
    -DBOARD_HAS_PSRAM
    -DDEBUG ;enable serial debugging

monitor_speed = 115200

lib_deps = 
    bblanchon/ArduinoJson